name: Pruebas Dinámicas de Seguridad (DAST)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip list  # Mostrar paquetes instalados
          pip check  # Verificar conflictos de dependencias

      - name: Iniciar aplicación Flask
        run: |
          export FLASK_APP_NAME=app
          export FLASK_ENV=development
          export SQLALCHEMY_DATABASE_URI=sqlite:///:memory:
          export DOMAIN=localhost
          flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          for i in {1..60}; do
            curl -s http://localhost:5000 && break
            echo "Esperando a que Flask inicie ($i/60)..."
            sleep 1
          done
          curl http://localhost:5000 || (echo "Error: No se pudo conectar a Flask"; cat flask.log; exit 1)

      - name: Mostrar logs de Flask si falla
        if: failure()
        run: |
          cat flask.log

      - name: Escaneo OWASP ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
          cmd_options: '-d'

      - name: Verificar directorio de trabajo
        run: |
          pwd
          ls -la

      - name: Verificar archivo generado
        run: |
          ls -l zap_baseline_report.json || echo "zap_baseline_report.json no encontrado"
          cat zap_baseline_report.json || echo "No se pudo leer zap_baseline_report.json"

      - name: Crear issue con resultados de ZAP
        if: success()  # Solo intenta crear issue si el escaneo fue exitoso
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('zap_baseline_report.json', 'utf8'));
            const alerts = report.site[0].alerts || [];
            const alertSummary = alerts.map(alert => `- ${alert.name}: ${alert.riskdesc} (${alert.count} instancias)`).join('\n');
            
            const issueTitle = 'ZAP Scan Baseline Report';
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['ZAP']
            });
            
            const issueExists = existingIssues.data.some(issue => issue.title === issueTitle);
            if (!issueExists) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: `## ZAP Scan Baseline Report\n\nResultados del escaneo de seguridad:\n${alertSummary}\n\nDetalles completos en el reporte adjunto.`,
                labels: ['ZAP', 'security']
              });
            } else {
              console.log('Issue ya existe, omitiendo creación.');
            }

      - name: Subir informe DAST
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_baseline_report.json
            report_html.html
            report_md.md