name: Pruebas Dinámicas de Seguridad (DAST)

on:
  push:
    branches: [ main ]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
      - name: Iniciar aplicación Flask
        run: |
          python app.py &  # Ajusta según tu archivo principal
          sleep 10
      - name: Escaneo OWASP ZAP 
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
      - name: Verificar directorio de trabajo
        run: |
          pwd
          ls -la
      - name: Verificar archivo generado
        run: |
          ls -l zap_baseline_report.json || echo "zap_baseline_report.json no encontrado"
          cat zap_baseline_report.json || echo "No se pudo leer zap_baseline_report.json"
      - name: Subir informe DAST
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_baseline_report.json