name: Seguridad en Infraestructura como C칩digo (IaC)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker/docker-compose.dev.yml'
      - '.github/workflows/iac.yml'

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Escanear Dockerfile
        run: |
          trivy fs --format json --output trivy_report.json . || echo '{"results": []}' > trivy_report.json

      - name: Verificar directorio de trabajo
        run: |
          pwd
          ls -la

      - name: Verificar archivo generado
        run: |
          ls -l trivy_report.json || echo "trivy_report.json no encontrado"
          cat trivy_report.json || echo "No se pudo leer trivy_report.json"

      - name: Instalar jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Crear engagement en DefectDojo
        env:
          DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        continue-on-error: true
        run: |
          TODAY=$(date +%Y-%m-%d)
          NEXT_WEEK=$(date -d "$TODAY +7 days" +%Y-%m-%d || date -v +7d +%Y-%m-%d)
          RESPONSE=$(curl --location --request POST "$DEFECTDOJO_URL/api/v2/engagements/" \
            -H "Authorization: Token $DEFECTDOJO_TOKEN" \
            -H "Content-Type: application/json" \
            --data-raw '{
              "name": "IaC-Pipeline-${{ github.run_id }}",
              "description": "Escaneo IaC para commit ${{ github.sha }}",
              "product": "${{ secrets.DEFECTDOJO_PRODUCT_ID }}",
              "target_start": "'"$TODAY"'",
              "target_end": "'"$NEXT_WEEK"'",
              "engagement_type": "CI/CD",
              "status": "In Progress",
              "build_id": "${{ github.run_id }}",
              "commit_hash": "${{ github.sha }}",
              "branch_tag": "${{ github.ref_name }}",
              "version": "${{ github.sha }}",
              "deduplication_on_engagement": false
            }' || echo "Error al conectar con DefectDojo")
          if [[ "$RESPONSE" == *"Error al conectar con DefectDojo"* ]]; then
            echo "DefectDojo no est치 disponible. Continuando sin crear engagement."
            echo "DEFECTDOJO_ENGAGEMENT_ID=none" >> $GITHUB_ENV
          else
            ENGAGEMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
            if [ -z "$ENGAGEMENT_ID" ] || [ "$ENGAGEMENT_ID" = "null" ]; then
              echo "Error: No se pudo crear el engagement. Respuesta: $RESPONSE"
              echo "DEFECTDOJO_ENGAGEMENT_ID=none" >> $GITHUB_ENV
            else
              echo "Engagement creado con ID: $ENGAGEMENT_ID"
              echo "DEFECTDOJO_ENGAGEMENT_ID=$ENGAGEMENT_ID" >> $GITHUB_ENV
            fi
          fi

      - name: Subir informe a DefectDojo
        if: env.DEFECTDOJO_ENGAGEMENT_ID != 'none'
        env:
          DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          ENGAGEMENT_ID: ${{ env.DEFECTDOJO_ENGAGEMENT_ID }}
        continue-on-error: true
        run: |
          RESPONSE=$(curl --location --request POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@trivy_report.json" \
            -F "scan_type=Trivy Scan" \
            -F "engagement=$ENGAGEMENT_ID" \
            -F "verified=true" \
            -F "active=true" \
            -F "minimum_severity=Info" \
            -F "skip_duplicates=true" \
            -F "close_old_findings=false" || echo "Error al subir informe a DefectDojo")
          if [[ "$RESPONSE" == *"Error al subir informe a DefectDojo"* ]]; then
            echo "No se pudo importar el escaneo a DefectDojo."
          else
            echo "Respuesta de import-scan: $RESPONSE"
            TEST_ID=$(echo "$RESPONSE" | jq -r '.test')
            if [ -z "$TEST_ID" ] || [ "$TEST_ID" = "null" ]; then
              echo "Error: No se pudo importar el escaneo. Respuesta: $RESPONSE"
            else
              echo "Escaneo importado correctamente con Test ID: $TEST_ID"
            fi
          fi

      - name: Mostrar mensaje si DefectDojo no est치 disponible
        if: env.DEFECTDOJO_ENGAGEMENT_ID == 'none'
        run: |
          echo "No se pudo conectar con DefectDojo. El informe IaC est치 disponible como artefacto."

      - name: Subir informe IaC
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.json