name: Análisis de Composición de Código (SCA)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt o está vacío"
      - name: Instalar pip-audit
        run: pip install pip-audit
      - name: Escanear dependencias con pip-audit
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt --format json --output sca_report.json || echo '{"vulnerabilities": []}' > sca_report.json
          else
            echo '{"vulnerabilities": []}' > sca_report.json
          fi
      - name: Verificar archivo generado
        run: |
          ls -l sca_report.json || echo "sca_report.json no encontrado"
          cat sca_report.json || echo "No se pudo leer sca_report.json"
      - name: Subir informe SCA
        uses: actions/upload-artifact@v3
        with:
          name: sca-report
          path: sca_report.json